### ISSUE TITLE
[Feature Request] HydraEnter/Exit autocommands

### ISSUE THREAD

**Issue by benlubas** [nvim-island/hydra.nvim#8]
Firing `User` autocommands after a hydra gets activated/deactivated would be cool. My use case is using it to immediately refresh my status line which I use to show an active hydra:

<img width="1470" alt="image" src="https://github.com/nvim-island/hydra.nvim/assets/56943754/3870909a-677e-48a9-8770-4139a385c9bc">

Currently I have to wait for something else to refresh it (which isn't a big deal, it's just not _ideal_).

As far as implementation details, there should probably be 4 of these:
- `HydraEnterPre` - fire when we're about to enter but the hydra state hasn't changed at all
- `HydraEnterPost` - fire after the hydra is active
- `HydraLeavePre` - fire before the hydra is deactivated
- `HydraLeavePost` - fire after the hydra is deactivated

Each one could also include some data in the data field (see `:h nvim_exec_autocmds()`), though I'm not sure what type of data would be useful (I wouldn't need any for my use case)

**Comment by miversen33** [comment]
I've been toying with a feature like this as well (though I am not completely sure what I want it to do yet).

I am not sure I want to expose Commands though, I am more leaning towards an event system that can be hooked.
Hell that might already exist, I haven't dug too deep into the code of Hydra, I just forked it and patched some of the serious bugs lol.

**Comment by benlubas** [comment]
If it's there it's not documented so I assume it's not, though I haven't looked into the code yet either.

Hook type event system would work fine as well. Could be functionally equivalent to exposing autocommands, so I don't have a strong preference there.

Point me in a direction and I'll write it :P

**Comment by miversen33** [comment]
Lemme give it a think on what I feel the best approach is. Since hydra is already neovim only, I see little reason to expose vim events when it could be handled purely from lua land. That said, if a PR showed up that implemented this feature using vim events, I also would not reject it for that reason. 

Also thank you for the contributions :)

**Comment by miversen33** [comment]
@benlubas  I hate to do this but, can you resubmit this issue on the new repo? It seems that github's "transfer issue" option only works for transferring within the org, and since the new repo is outside this org, I cannot transfer it there
